unstable_features = true

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

imports_granularity = "Module"
group_imports = "StdExternalCrate"

use_field_init_shorthand = true

comment_width = 115
wrap_comments = true

max_width = 115
use_small_heuristics = "Max"
struct_lit_width = 60
struct_variant_width = 60
